### ISSUE TITLE
Bonferroni correction

### ISSUE THREAD

**Issue by rayglover-ibm** [gerbenvoshol/Statistics-Tool-Box#2]
I believe the formula used in `stb_bonferroni` is not the Bonferroni but the Šidák correction:
https://github.com/gerbenvoshol/Statistics-Tool-Box/blob/0b69bd183e8938c4f1e2bd50bdf3d2d5adf6e0f3/stb_stats.h#L2769

(Thank you for this project!)

**Comment by gerbenvoshol** [comment]
Thanks! You are correct. I changed the function name to reflect the actual correction used.
